# Generated by Django 5.1.4 on 2025-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
